plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.snesemulator'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.snesemulator"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17 -O3"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }
}
